#!/bin/bash

export RESOURCE_GROUP="cgament-llmd-rg-1"
export CLUSTER_NAME="cgament-llmd-cluster-1"
export LOCATION="eastus"
export GPU_SKU="Standard_NC4as_T4_v3"
export CONTROL_SKU="Standard_D5_v2"
export NODE_COUNT=1
export HF_TOKEN="SECRET"
export SSH_KEY_FILE="${HOME}/.ssh/azure.pub"
export GPU_OPERATOR_VERSION="v25.10.0"
export LLMD_VERSION="v0.3.1"
export LLMD_NAMESPACE="llm-d"
